SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES 
FROM BOOK AS B
LEFT JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
LEFT JOIN BOOK_SALES AS BS ON BS.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC