SELECT YEAR(S.SALES_DATE) AS YEAR,
        MONTH(S.SALES_DATE) AS MONTH,
        I.GENDER,
        COUNT(DISTINCT S.USER_ID) AS 'USERS'
FROM ONLINE_SALE AS S
LEFT JOIN USER_INFO AS I ON S.USER_ID = I.USER_ID
GROUP BY YEAR(S.SALES_DATE),
        MONTH(S.SALES_DATE),
        I.GENDER
HAVING I.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, I.GENDER
