SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH,
        COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
        ROUND(
        COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 
        1
    ) AS PURCHASED_RATIO
FROM ONLINE_SALE AS S
INNER JOIN (
    SELECT * FROM USER_INFO WHERE YEAR(JOINED) = '2021'
    ) AS I ON S.USER_ID = I.USER_ID
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY YEAR, MONTH

