WITH RECURSIVE GenerationCTE AS (
    -- 1단계: 1세대 추출 (Anchor)
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 2단계: 재귀적으로 다음 세대 계산 (Recursive)
    SELECT e.ID, e.PARENT_ID, g.GENERATION + 1
    FROM ECOLI_DATA e
    INNER JOIN GenerationCTE g ON e.PARENT_ID = g.ID
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM GenerationCTE
WHERE ID NOT IN (
    -- 자식이 있는 ID(즉, 누군가의 PARENT_ID인 ID)를 제외
    SELECT DISTINCT PARENT_ID 
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION ASC;