SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B
LEFT JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
WHERE B.WRITER_ID IN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE' 
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) AND B.STATUS = 'DONE'
GROUP BY U.USER_ID
ORDER BY TOTAL_SALES ASC