SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO AS II
LEFT JOIN ITEM_TREE AS IT ON
    II.ITEM_ID = IT.ITEM_ID
LEFT JOIN ITEM_INFO AS IC ON
    IT.PARENT_ITEM_ID = IC.ITEM_ID
WHERE IT.PARENT_ITEM_ID IS NOT NULL AND IC.RARITY = 'RARE'
ORDER BY II.ITEM_ID DESC