SELECT C.ID, C.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS C
INNER JOIN ECOLI_DATA AS P ON C.PARENT_ID = P.ID
-- 자식(C)과 부모(P)를 AND 연산했을 때, 부모(P)의 형질이 그대로 남아야 함
WHERE (C.GENOTYPE & P.GENOTYPE) = P.GENOTYPE
ORDER BY C.ID ASC;