SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE ANIMAL_ID IN (
    SELECT I.ANIMAL_ID
    FROM ANIMAL_INS AS I
    INNER JOIN  ANIMAL_OUTS AS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    WHERE O.DATETIME <= I.DATETIME
    ) 
ORDER BY DATETIME ASC