SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
  AND CAR_ID IN (
    -- 1. 8월~10월 사이 총 대여 횟수가 5회 이상인 CAR_ID만 추출
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
  )
GROUP BY MONTH, CAR_ID
-- 2. 특정 월의 대여 횟수가 0인 경우는 제외 (COUNT가 0보다 큰 것만 표시)
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC;