# SELECT A.FLAVOR FROM FIRST_HALF A
# JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR
# WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based';

SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
JOIN ICECREAM_INFO AS II ON FH.FLAVOR = II.FLAVOR
WHERE FH.TOTAL_ORDER > 3000 AND II.INGREDIENT_TYPE = 'fruit_based'